name: deploy to gh pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node@3
        with:
          node-version: '19'
      - run: 'corepack enable'
      - run: pnpm --version
      - run: pnpm node --version
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: actions/upload-pages-artifacts@v1
        with:
          path: ./out
  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: build-gh-pages
    environment:
      name: github-pages
      url:  ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1